version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: manage
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # Define a senha do root
      MYSQL_DATABASE: manage
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
